# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/myCollege/ComputerSystem/NSCSCC/NSCSCC/NSCSCC/PersonalProgress/HaitianJiang/SingleMiniSys/mycpu_design/mycpu_design.srcs/sources_1/ip/instROM/instROM.xci
# IP: The module: 'instROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/myCollege/ComputerSystem/NSCSCC/NSCSCC/NSCSCC/PersonalProgress/HaitianJiang/SingleMiniSys/mycpu_design/mycpu_design.srcs/sources_1/ip/instROM/instROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/myCollege/ComputerSystem/NSCSCC/NSCSCC/NSCSCC/PersonalProgress/HaitianJiang/SingleMiniSys/mycpu_design/mycpu_design.srcs/sources_1/ip/instROM/instROM.xci
# IP: The module: 'instROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/myCollege/ComputerSystem/NSCSCC/NSCSCC/NSCSCC/PersonalProgress/HaitianJiang/SingleMiniSys/mycpu_design/mycpu_design.srcs/sources_1/ip/instROM/instROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
